### ISSUE TITLE
error when pressing enter

### ISSUE THREAD

**Issue by JuniorzGTX** [Cracko298/Sharkbite-2-Farmer#4]
Traceback (most recent call last):
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyautogui\__init__.py", line 204, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyscreeze\__init__.py", line 447, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.785)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\junio\Downloads\AFK-Tool\afk-tool.py", line 55, in <module>
    afk0 = pyautogui.locateCenterOnScreen('_afk0.png', confidence=0.9)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\junio\miniconda3\Lib\site-packages\pyautogui\__init__.py", line 174, in wrapper
    raise ImageNotFoundException  # Raise PyAutoGUI's ImageNotFoundException.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyautogui.ImageNotFoundException

**Comment by JuniorzGTX** [comment]
tried NP version, works but doesnt do anything

**Comment by Cracko298** [comment]
Sorry you're having trouble with the Farmer.
I looked over the produced Error, I found out it's a bug with the Confidense Level of the Script.

This basically means the max value of an image found on screen that is identical is about 78.5% in this error case.

When I get a chance, I'll update the script to change and check for these extra Lower Confidense errors.

Thank you for submitting this error, and I will get on it as soon as I possibly can.
Will keep this open until resolved.
